### ISSUE TITLE
Cannot load vacuums after update to HA 2022.03.2

### ISSUE THREAD

**Issue by jeremysherriff** [KrzysztofHajdamowicz/home-assistant-vacuum-styj02ym#29]
I didn't update to 2022.3.0 because of the broken UI components, so I'm unsure exactly what Hass.io version broke this - I assume it's all 2022.3.x.
Now that I have updated, devices defined for this integration won't load.

Log snippet:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 877, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 572, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 589, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/miio2/vacuum.py", line 6, in <module>
    from miio import DeviceException, Vacuum  # pylint: disable=import-error
ImportError: cannot import name 'Vacuum' from 'miio' (/usr/local/lib/python3.9/site-packages/miio/__init__.py)
```

I cannot reload configuration, because:
```
The system cannot restart because the configuration is not valid: Platform error vacuum.miio2 - cannot import name 'Vacuum' from 'miio' (/usr/local/lib/python3.9/site-packages/miio/__init__.py) Platform error vacuum.miio2 - cannot import name 'Vacuum' from 'miio' (/usr/local/lib/python3.9/site-packages/miio/__init__.py)
```

Is there anything further I can provide to assist in identifying the fault?

**Comment by jeremysherriff** [comment]
Problem solved, notes for others:

After my update to Hass.io 2202.3.x there were a number of additional repos with updates available under HACS.  Most were frontend components, but one was a Xiaomi integration for Smart Power Plugs. It looks like [this commit](https://github.com/syssi/xiaomiplug/commit/4e69bbfacc6169609175ac3227995f26155abeda) bumps `python-miio` to `0.5.10` and to the best of my knowledge, that is what caused the incompatibility as this repo uses `0.5.9.1`.

I don't understand how HA (or HACS?) deals with competing dependencies, so I have no idea if this was expected or unexpected behaviour.

I have now fixed my issue using the following steps;
1. Comment out the YAML for all vacuums that use this integration
2. Remove this integration from HACS
3. Restart HA
4. Reinstall this integration in HACS
5. Restart HA
6. Re-enable YAML for the vacuums
7. Restart HA

All components are working.

Cheers
